### ISSUE TITLE
Endpoints

### ISSUE THREAD

**Issue by XeraFiu-YTB** [guime7000/VR_bot#1]
Bonsoir, j'ai vu vos différents repos liés à l'utilisation de l'API VR sur Github. Dans votre code vous affichez publiquement le fonctionnement de l'API avec les différents Endpoints. Vous devriez rassembler en un seul fichier les différents endpoints et le supprimer de Github pour éviter tout mauvais usage de la part d'une personne malveillante.

**Comment by XeraFiu-YTB** [comment]
J'ai vu votre profil Linkedin, si jamais vous avez besoin d'aide sur vos différents projets n'hésitez pas à me contacter

**Comment by guime7000** [comment]
Bonjour,

Je pense avoir résolu le problème.

**Comment by guime7000** [comment]
Bonsoir Nathan,

Erreur corrigée (un peu brutalement en restant le repo donc votre issue à
disparu).

Les endpoints de cette api sont loiiiiinnnnnn d'être confidentiels, mais
autant que ce ne soit pas "gràce" à mon repo que qqch arrive !

Bonne soirée,

Thomas.

Le ven. 4 nov. 2022 à 17:51, Nathan Bastard ***@***.***> a
écrit :
